apiVersion: batch/v1
kind: CronJob
metadata:
  name: petrosa-crypto-binance-current-klines-5m-history
spec:
  schedule: "1,6,11,16,21,26,31,36,41,46,51,56 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 300
          containers:
          - name: petrosa-apps-jobs
            image: yurisa2/petrosa-apps-jobs:v0.0.90
            env:
              - name: PERIOD
                value: "5m"
              - name: VERSION
                value: "0.0.90"
              - name: OTEL_SERVICE_NAME
                value: "petrosa-crypto-binance-current-klines-5m-history"

            envFrom:
              - configMapRef:
                  name: petrosa-apps-configmap


            imagePullPolicy: Always
            command: ["opentelemetry-instrument", "python"]
            args: ["./petrosa_binance_current_klines/main.py"]
          restartPolicy: Never
